-----------------------------------------------------------------------------------------------------------------
--Insert PickList Type Data
Exec dw.spInsertPickListType 'Security_Identifier_Type',	'Security_Identifier_Type'
Exec dw.spInsertPickListType 'Coupon_Type',					'Coupon_Type'
Exec dw.spInsertPickListType 'Frequency_Type',				'Frequency_Type'
Exec dw.spInsertPickListType 'Root_Yellowkey',				'Root_Yellowkey'
Exec dw.spInsertPickListType 'Country_Code_Type',			'Country_Code_Type'
Exec dw.spInsertPickListType 'Option_Exercise_Type',		'Option_Exercise_Type'
Exec dw.spInsertPickListType 'Option_Under_Type',			'Option_Under_Type'
Exec dw.spInsertPickListType 'Option_Type',					'Option_Type'
Exec dw.spInsertPickListType 'Day_Count',					'Day_Count'
Exec dw.spInsertPickListType 'Account_Fee_Rate_Type',		'Account_Fee_Rate_Type'
Exec dw.spInsertPickListType 'Futures_Month_Code',			'Futures_Month_Code'
Exec dw.spInsertPickListType 'Futures_Type',				'Futures_Type'
Exec dw.spInsertPickListType 'Calculation_Measure',			'Calculation_Measure'

-----------------------------------------------------------------------------------------------------------------
--Insert PickList Data
Exec dw.spInsertPickList 'Security_Identifier_Type',	'CUSIP',							'CUSIP Symbol' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'SEDOL',							'SEDOL Symbol' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'ISIN',								'ISIN Symbol' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'MGR_Sec_ID',						'Manager Security ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'LOANX ID',							'LoanX ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'BB Desc',							'Bloomberg Name ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'BBGID',							'Bloomberg Bsym Global ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'BBGID - Domestic',					'Bloomberg Bsym Domestic ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'BBGID - Alternative',				'Bloomberg Bsym Alnsert PickListternative Global ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Ticker_BB',						'Ticker Bloomberg' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Ticker_BB with yellow key',		'Ticker with Bloomberg Yellow Key' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Ticker_BB with exchange code',		'Ticker with Bloomberg Exchange' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Ticker_FDS',						'Ticker FactSet' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Ticker_FDS with exchange code',	 'Ticker w/FactSet Exchange' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'VALOREN',							'Valoren ID' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'REDCODE',							'Red Code' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'Loan ID Number',					'LIN Number' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'OCC Code',							'Options OCC Code' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'OPRA Code',						'Options OPRA Code' 
Exec dw.spInsertPickList 'Security_Identifier_Type',	'FOS ID',							'FactSet Options Symbol' 

Exec dw.spInsertPickList 'Coupon_Type', 'Fixed',	'Fixed Coupon'
Exec dw.spInsertPickList 'Coupon_Type', 'Variable', 'Variable Coupon Type'
Exec dw.spInsertPickList 'Coupon_Type', 'Zero',		'Zero Coupon Bond'
Exec dw.spInsertPickList 'Coupon_Type', 'Floating',	'Floating Coupon Type'
Exec dw.spInsertPickList 'Coupon_Type', 'Step',		'Stepped Coupon Type'
Exec dw.spInsertPickList 'Coupon_Type', 'Defaulted', 'Defaulted Status'

Exec dw.spInsertPickList 'Frequency_Type',	'D',	'Daily'
Exec dw.spInsertPickList 'Frequency_Type',	'W',	'Weekly'
Exec dw.spInsertPickList 'Frequency_Type',	'AW',	'Actual Weekly'
Exec dw.spInsertPickList 'Frequency_Type',	'M',	'Monthly'
Exec dw.spInsertPickList 'Frequency_Type',	'AM',	'Actual Monthly'
Exec dw.spInsertPickList 'Frequency_Type',	'MTD',	'Month to Date'
Exec dw.spInsertPickList 'Frequency_Type',	'Q',	'Quarterly'
Exec dw.spInsertPickList 'Frequency_Type',	'AQ',	'Actual Quarter'
Exec dw.spInsertPickList 'Frequency_Type',	'FQ',	'Fiscal Quarter'
Exec dw.spInsertPickList 'Frequency_Type',	'SA',	'Semi-Annual'
Exec dw.spInsertPickList 'Frequency_Type',	'ASA',	'Actual Semi-Annual'
Exec dw.spInsertPickList 'Frequency_Type',	'FSA',	'Fiscal Semi-Annual'
Exec dw.spInsertPickList 'Frequency_Type',	'Y',	'Year'
Exec dw.spInsertPickList 'Frequency_Type',	'AY',	'Actual Year'

Exec dw.spInsertPickList 'Root_Yellowkey',	'GOVT',		'Government Bond'
Exec dw.spInsertPickList 'Root_Yellowkey',	'CORP',		'Corporate'
Exec dw.spInsertPickList 'Root_Yellowkey',	'MTGE',		'ABS'
Exec dw.spInsertPickList 'Root_Yellowkey',	'MUNI',		'Municipal Bond'
Exec dw.spInsertPickList 'Root_Yellowkey',	'PFD',		'Preferred'
Exec dw.spInsertPickList 'Root_Yellowkey',	'COMDTY',	'Commodity'
Exec dw.spInsertPickList 'Root_Yellowkey',	'CURNCY',	'Currency'
Exec dw.spInsertPickList 'Root_Yellowkey',	'EQUITY',	'Equity'
Exec dw.spInsertPickList 'Root_Yellowkey',	'M-Mkt',	'Money Market'
Exec dw.spInsertPickList 'Root_Yellowkey',	'INDEX',	'Index'
 
Exec dw.spInsertPickList 'Country_Code_Type', 'FDS',	'FactSet'
Exec dw.spInsertPickList 'Country_Code_Type', 'MSCI',	'MSCI'
Exec dw.spInsertPickList 'Country_Code_Type', 'LH',		'Barclays'
Exec dw.spInsertPickList 'Country_Code_Type', 'ML',		'Merrill Lynch'
Exec dw.spInsertPickList 'Country_Code_Type', 'SP',		'S&P'
Exec dw.spInsertPickList 'Country_Code_Type', 'BICS',	'Bloomberg'
Exec dw.spInsertPickList 'Country_Code_Type', 'ICB',	'FTSE'
Exec dw.spInsertPickList 'Country_Code_Type', 'RGS',	'Russell'
Exec dw.spInsertPickList 'Country_Code_Type', 'SIC',	'SIC'
Exec dw.spInsertPickList 'Country_Code_Type', 'NAIC',	'NAICS'


Exec dw.spInsertPickList 'Option_Exercise_Type', 'A', 'American'
Exec dw.spInsertPickList 'Option_Exercise_Type', 'E', 'European'

Exec dw.spInsertPickList 'Option_Under_Type',	'id',	'Equity Index'
Exec dw.spInsertPickList 'Option_Under_Type',	'cm',	'Commodity Index'
Exec dw.spInsertPickList 'Option_Under_Type',	'ir',	'Interest Rate'
Exec dw.spInsertPickList 'Option_Under_Type',	'gb',	'Government Bond'
Exec dw.spInsertPickList 'Option_Under_Type',	'fu',	'Future'
Exec dw.spInsertPickList 'Option_Under_Type',	'fx',	'Currency'
Exec dw.spInsertPickList 'Option_Under_Type',	'fi',	'Bond'
Exec dw.spInsertPickList 'Option_Under_Type',	'eq',	'Equity'

Exec dw.spInsertPickList  'Option_Type', 'C', 'CALL'
Exec dw.spInsertPickList  'Option_Type', 'P', 'PUT'

Exec dw.spInsertPickList 'Day_Count',	'28/360',		'28/360'
Exec dw.spInsertPickList 'Day_Count',	'30/360',		'30/360'
Exec dw.spInsertPickList 'Day_Count',	'30/365',		'30/365'
Exec dw.spInsertPickList 'Day_Count',	'30/ACT',		'30/ACT'
Exec dw.spInsertPickList 'Day_Count',	'30E/360',		'EuroBond Basis'
Exec dw.spInsertPickList 'Day_Count',	'30E/365',		'EuroBond Basis'
Exec dw.spInsertPickList 'Day_Count',	'30E/ACT',		'EuroBond Basis'
Exec dw.spInsertPickList 'Day_Count',	'30I/ACT',		'30I/ACT (ISDA)'
Exec dw.spInsertPickList 'Day_Count',	'30I/360',		'30I/360 (ISDA)'
Exec dw.spInsertPickList 'Day_Count',	'30I/365',		'30I/365 (ISDA)'
Exec dw.spInsertPickList 'Day_Count',	'ACT/360',		'ACTUAL/360'
Exec dw.spInsertPickList 'Day_Count',	'ACT/364',		'ACT/364'
Exec dw.spInsertPickList 'Day_Count',	'ACT/365',		'ACTUAL/365'
Exec dw.spInsertPickList 'Day_Count',	'ACT/ACT',		'ACTUAL/ACTUAL (366)'
Exec dw.spInsertPickList 'Day_Count',	'BUS/252',		'BUSINESS DAYS/252 '
Exec dw.spInsertPickList 'Day_Count',	'NL/ACT',		'No Leap Year/Actual'
Exec dw.spInsertPickList 'Day_Count',	'NL/360',		'No Leap Year/360'
Exec dw.spInsertPickList 'Day_Count',	'NL/365',		'No Leap Year/365'
Exec dw.spInsertPickList 'Day_Count',	'Act/365.Fixe',	'Act/365.Fixe'

Exec dw.spInsertPickList 'Futures_Month_Code','F',	'January'
Exec dw.spInsertPickList 'Futures_Month_Code','G',	'February'
Exec dw.spInsertPickList 'Futures_Month_Code','H',	'March'
Exec dw.spInsertPickList 'Futures_Month_Code','J',	'April'
Exec dw.spInsertPickList 'Futures_Month_Code','K',	'May'
Exec dw.spInsertPickList 'Futures_Month_Code','M',	'June'
Exec dw.spInsertPickList 'Futures_Month_Code','N',	'July'
Exec dw.spInsertPickList 'Futures_Month_Code','Q',	'August'
Exec dw.spInsertPickList 'Futures_Month_Code','U',	'September'
Exec dw.spInsertPickList 'Futures_Month_Code','V',	'October'
Exec dw.spInsertPickList 'Futures_Month_Code','X',	'November'
Exec dw.spInsertPickList 'Futures_Month_Code','Z',	'December'


Exec dw.spInsertPickList 'Futures_Type','id',	'Index Futures'
Exec dw.spInsertPickList 'Futures_Type','cm',	'Commodity Futures'
Exec dw.spInsertPickList 'Futures_Type','ir',	'Interest Rate Futures'
Exec dw.spInsertPickList 'Futures_Type','gb',	'Government Bond Futures'
Exec dw.spInsertPickList 'Futures_Type','fx',	'Currency Futures'
Exec dw.spInsertPickList 'Futures_Type','fi',	'Bond Futures'
Exec dw.spInsertPickList 'Futures_Type','eq',	'Equity Futures'
Exec dw.spInsertPickList 'Futures_Type','ag',	'Agriculture Futures'
Exec dw.spInsertPickList 'Futures_Type','en',	'Energy Futures'
Exec dw.spInsertPickList 'Futures_Type','me',	'Metals Futures'
Exec dw.spInsertPickList 'Futures_Type','re',	'Real Estate Futures'

Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE1_Proxy',	'FEE 1 Proxy'
Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE1_AUM',	'FEE 1 AUM'
Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE2_Proxy',	'FEE 2 Proxy'
Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE2_AUM',	'FEE 2 AUM'
Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE3_Proxy',	'FEE 3 Proxy'
Exec dw.spInsertPickList 'Account_Fee_Rate_Type','FEE3_AUM',	'FEE 3 AUM'

Exec dw.spInsertPickList 'Calculation_Measure',	'BNY Calculated',			'1 to 1 Mapping'
Exec dw.spInsertPickList 'Calculation_Measure',	'BNY Derived -MD',			'BNY Derived -Modified Dietz'
Exec dw.spInsertPickList 'Calculation_Measure',	'BNY Derived -PCHG'	,		'BNY Derived -Percentage Changes'
Exec dw.spInsertPickList 'Calculation_Measure',	'BNY Derived -MD -EOD',		'BNY Derived -Modified Dietz (CF at End of Day)'
Exec dw.spInsertPickList 'Calculation_Measure',	'BNY Derived -MD -MOD',		'BNY Derived -Modified Dietz (CF at Mid of Day)'
Exec dw.spInsertPickList 'Calculation_Measure',	'Account - Contribution',	'Account Contribution Estimated Performance'
Exec dw.spInsertPickList 'Calculation_Measure',	'Holdings Derived - PCHG',	'Account Derived Performance by PCHG'
Exec dw.spInsertPickList 'Calculation_Measure',	'Holdings Derived - Contr',	'Account Derived Performance by Contribution'

----------------------------------------------------------------------------------------------------------------